version: '3.8'
services:
  gmgo-admin-api:
    container_name: gmgo-admin
    image: gmgo-admin:latest
    privileged: true
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./config/:/gmgo-admin-api/config/
      - ./static/:/gmgo-admin-api/static/
      - ./temp/:/gmgo-admin-api/temp/
    networks:
      - myweb
networks:
  myweb:
    driver: bridge

